# Book settings
title: Guide to self-host Overleaf Community Edition
author: Dr Shihab Khan

repository:
  url: https://github.com/shihabkhan1/overleaf
  path_to_book: docs  # Optional path to your book,

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: force
